//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public approval()
        {
            this.leaves = new HashSet<leave>();
        }
    
        public int id { get; set; }
        public Nullable<int> approvalType { get; set; }
        public string approvalStatus { get; set; }
        public int approvalIdv { get; set; }
        public Nullable<int> approvalby { get; set; }
        public Nullable<int> approvalQ { get; set; }
        public string approvalMail { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public string rowStatus { get; set; }
        public string rowDate { get; set; }
    
        public virtual emp_master emp_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leave> leaves { get; set; }
    }
}
