//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoryfile
    {
        public int id { get; set; }
        public Nullable<int> idv { get; set; }
        public string type { get; set; }
        public byte[] image { get; set; }
        public string description { get; set; }
    }
}
