//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_contact
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public string UID { get; set; }
        public string contact1 { get; set; }
        public string contact2 { get; set; }
        public string contact3 { get; set; }
        public string contact4 { get; set; }
        public string contact_temp { get; set; }
        public string rowStatus { get; set; }
        public string lastUpdate { get; set; }
    }
}
