//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_address
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public string UID { get; set; }
        public string Address { get; set; }
        public string Kelurahan { get; set; }
        public Nullable<long> Kecamatan { get; set; }
        public Nullable<long> Kabupaten { get; set; }
        public Nullable<long> Provinsi { get; set; }
        public Nullable<int> Country { get; set; }
        public string rowStatus { get; set; }
    }
}
