//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emp_master()
        {
            this.approvals = new HashSet<approval>();
            this.balances = new HashSet<balance>();
            this.emp_image = new HashSet<emp_image>();
            this.emp_user = new HashSet<emp_user>();
            this.files = new HashSet<file>();
            this.leaves = new HashSet<leave>();
            this.leaves1 = new HashSet<leave>();
            this.organizations = new HashSet<organization>();
            this.organizations1 = new HashSet<organization>();
            this.roles = new HashSet<role>();
            this.timesheets = new HashSet<timesheet>();
            this.timesheets1 = new HashSet<timesheet>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDParent { get; set; }
        public Nullable<int> IDParentLevel { get; set; }
        public string UID { get; set; }
        public string NIP { get; set; }
        public Nullable<int> UID_ABSENCE { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string Marital { get; set; }
        public string Birthplace { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Nationality { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string AddressKel { get; set; }
        public Nullable<long> AddressKec { get; set; }
        public Nullable<long> AddressKab { get; set; }
        public Nullable<long> AddressProv { get; set; }
        public Nullable<long> AddressCountry { get; set; }
        public Nullable<int> empEdu { get; set; }
        public string empEduMajor { get; set; }
        public string empStatus { get; set; }
        public Nullable<int> empPosition { get; set; }
        public Nullable<int> empJobLevel { get; set; }
        public Nullable<int> empDivision { get; set; }
        public Nullable<int> empDepartement { get; set; }
        public string empOfficeLocation { get; set; }
        public string Contact { get; set; }
        public string rowStatus { get; set; }
        public System.DateTime lastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approval> approvals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<balance> balances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_image> emp_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_user> emp_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leave> leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leave> leaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organization> organizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organization> organizations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role> roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timesheet> timesheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timesheet> timesheets1 { get; set; }
    }
}
