//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_birth
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public string UID { get; set; }
        public string BIRTH_PLACE { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<int> NATIONALITY { get; set; }
        public string rowStatus { get; set; }
        public string lastUpdate { get; set; }
    }
}
