//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_edu
    {
        public int ID { get; set; }
        public int IDV { get; set; }
        public string UID { get; set; }
        public Nullable<int> edu { get; set; }
        public string Latest_Edu { get; set; }
        public string Latest_Major { get; set; }
        public string rowStatus { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    }
}
