//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int ID { get; set; }
        public int IDV { get; set; }
        public Nullable<int> CATTYPE { get; set; }
        public byte[] CONTENT { get; set; }
        public string CONTENTTYPE { get; set; }
        public string FILETYPE { get; set; }
        public byte[] FILENAME { get; set; }
    
        public virtual emp_master emp_master { get; set; }
    }
}
