//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave
    {
        public int id { get; set; }
        public Nullable<int> leaveCategory { get; set; }
        public Nullable<int> idvRequest { get; set; }
        public Nullable<int> idvApproval { get; set; }
        public Nullable<System.DateTime> leaveStart { get; set; }
        public Nullable<System.DateTime> leaveStop { get; set; }
        public Nullable<int> appliedDay { get; set; }
        public Nullable<System.TimeSpan> appliedTime { get; set; }
        public Nullable<int> remainDay { get; set; }
        public Nullable<System.TimeSpan> remainTime { get; set; }
        public Nullable<int> currBalance { get; set; }
        public Nullable<int> approvalID { get; set; }
        public string rowStatus { get; set; }
        public Nullable<System.DateTime> rowDate { get; set; }
    
        public virtual approval approval { get; set; }
        public virtual category category { get; set; }
        public virtual emp_master emp_master { get; set; }
        public virtual emp_master emp_master1 { get; set; }
    }
}
