//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locationparent
    {
        public int id { get; set; }
        public Nullable<int> uidparent { get; set; }
        public Nullable<int> uidtype { get; set; }
        public string uidname { get; set; }
    }
}
