//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterHRISEntities : DbContext
    {
        public MasterHRISEntities()
            : base("name=MasterHRISEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
            this.Database.Log = s => System.Diagnostics.Debug.WriteLine(s);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<locationparent> locationparents { get; set; }
        public virtual DbSet<approval> approvals { get; set; }
        public virtual DbSet<balance> balances { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<categoryfile> categoryfiles { get; set; }
        public virtual DbSet<categoryparent> categoryparents { get; set; }
        public virtual DbSet<emp_address> emp_address { get; set; }
        public virtual DbSet<emp_birth> emp_birth { get; set; }
        public virtual DbSet<emp_contact> emp_contact { get; set; }
        public virtual DbSet<emp_edu> emp_edu { get; set; }
        public virtual DbSet<emp_image> emp_image { get; set; }
        public virtual DbSet<emp_job> emp_job { get; set; }
        public virtual DbSet<emp_master> emp_master { get; set; }
        public virtual DbSet<emp_master_absence> emp_master_absence { get; set; }
        public virtual DbSet<emp_phone> emp_phone { get; set; }
        public virtual DbSet<emp_user> emp_user { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<leave> leaves { get; set; }
        public virtual DbSet<leave_master> leave_master { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<medical> medicals { get; set; }
        public virtual DbSet<medical_fee> medical_fee { get; set; }
        public virtual DbSet<notifnew> notifnews { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<ref_dep> ref_dep { get; set; }
        public virtual DbSet<ref_div> ref_div { get; set; }
        public virtual DbSet<ref_edu> ref_edu { get; set; }
        public virtual DbSet<ref_empStatus> ref_empStatus { get; set; }
        public virtual DbSet<ref_joblevel> ref_joblevel { get; set; }
        public virtual DbSet<ref_personrole> ref_personrole { get; set; }
        public virtual DbSet<ref_pos> ref_pos { get; set; }
        public virtual DbSet<ref_typeleave> ref_typeleave { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<timesheet> timesheets { get; set; }
        public virtual DbSet<Table_2> Table_2 { get; set; }
    }
}
