//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_fee
    {
        public int MEDICAL_ID { get; set; }
        public Nullable<int> LEAVE_ID { get; set; }
        public Nullable<decimal> FEE_DOCTOR { get; set; }
        public Nullable<decimal> FEE_MEDICINE { get; set; }
        public Nullable<decimal> FEE_TOTAL { get; set; }
        public Nullable<decimal> FEE_CLAIM { get; set; }
        public string ROWSTATUS { get; set; }
        public byte[] ROWDATE { get; set; }
    }
}
