//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical
    {
        public int id { get; set; }
        public Nullable<int> medicalID { get; set; }
        public int idvRequest { get; set; }
        public int idvApproval { get; set; }
        public string typeDoctor { get; set; }
        public string typeClaim { get; set; }
        public Nullable<int> feeDoctor { get; set; }
        public Nullable<int> feeMedicine { get; set; }
        public Nullable<int> feeTotal { get; set; }
        public Nullable<int> feeClaimable { get; set; }
        public string rowStatus { get; set; }
        public Nullable<System.DateTime> rowDate { get; set; }
    }
}
