//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notifnew
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> cattype { get; set; }
        public string filepath { get; set; }
        public byte[] filename { get; set; }
        public Nullable<int> lastupdateby { get; set; }
        public Nullable<System.TimeSpan> lastupdate { get; set; }
    }
}
