//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_personrole
    {
        public int PERSONROLE_ID { get; set; }
        public string PERSONROLE_TYPE { get; set; }
        public string PERSONROLE_DESC { get; set; }
    }
}
