//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public Nullable<int> IDVAPPROVAL { get; set; }
        public Nullable<System.DateTime> WORKIN { get; set; }
        public Nullable<System.DateTime> WORKOUT { get; set; }
        public Nullable<System.DateTime> WORKDURATION { get; set; }
        public Nullable<System.DateTime> INADJUSTED { get; set; }
        public Nullable<System.DateTime> OUTADJUSTED { get; set; }
        public Nullable<System.DateTime> DATEADJUSTED { get; set; }
        public Nullable<System.DateTime> DATEAPPROVED { get; set; }
        public string REASON { get; set; }
    
        public virtual emp_master emp_master { get; set; }
        public virtual emp_master emp_master1 { get; set; }
    }
}
