//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_R01.Models.Session
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_user
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public string IDVMAIL { get; set; }
        public Nullable<int> IDVROLE { get; set; }
        public string IDVMAILPASSWORD { get; set; }
    }
}
