//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRIS_R01.Models.Session
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_user
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public string IDVMAIL { get; set; }
        public Nullable<int> IDVROLE { get; set; }
        public string PASSWORD { get; set; }
    }

    public class LoginModel
    {
        [Required]
        [Display(Name = "EMAIL")]
        public string IDVMAIL { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "PASSWORD")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}
